version: '3.7'

networks:
  production:

services:

  backend:
    build:
      context: .
      target: production
    container_name: image-generator
    ports:
      - "3000:3000"
      - "8080:8080"
      - "6001:6001"
    env_file:
      - .env
    networks:
      - production

