version: '3.7'

networks:
  production:

services:

  backend:
    build:
      context: .
      target: production
    container_name: image-generator
    ports:
      - "3000:3000"
      - "8080:8080"
      - "6001:6001"
    env_file:
      - .env
    networks:
      - production
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - "5432:5432"
    networks:
      - production


  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: $MINIO_USERNAME
      MINIO_ROOT_PASSWORD: $MINIO_PASSWORD
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data:
  minio-storage: